### ISSUE TITLE
ovirt_engine_type should have default value ovirt-engine

### ISSUE THREAD

**Issue by StLuke** [StLuke/ovirt-ansible#28]

**Comment by StLuke** [comment]
the same for ovirt_engine_admin_password

**Comment by pkubica** [comment]
default type is 'ovirt-engine' (reason: for yum install 'ovirt-engine')

**Comment by StLuke** [comment]
bug?
https://github.com/StLuke/ovirt-ansible/blob/master/roles/ovirt-common/defaults/main.yml

**Comment by pkubica** [comment]
yes, my pull (from remote-db) will solve it.
