### ISSUE TITLE
Remove {{variables}} from role and task names

### ISSUE THREAD

**Issue by StLuke** [StLuke/ovirt-ansible#31]
Remove variables from task names -> ovirt

TASK [ovirt-common : create repository backup] *********************************
changed: [192.168.1.1]

TASK [ovirt-common : copy {{ovirt_engine_type}} repository file] ***************
skipping: [192.168.1.1]

TASK [ovirt-engine-install-packages : yum install {{ovirt_engine_type}} engine] 
ok: [192.168.1.1]

**Comment by pkubica** [comment]
Already done.
