### ISSUE TITLE
Need fix Travis CI

### ISSUE THREAD

**Issue by pkubica** [StLuke/ovirt-ansible#39]
"The repository at StLuke/rhevm-ansible was not found."
- maybe just change URLs in README.md

**Comment by StLuke** [comment]
Can you provide any link for build with this isssue?

**Comment by pkubica** [comment]
master -> see main page (missing build status)

**Comment by pkubica** [comment]
https://github.com/StLuke/ovirt-ansible (left top of readme)

**Comment by StLuke** [comment]
PR #40

**Comment by pkubica** [comment]
perfect
